version: '3'

services:
  redis:
    image: 'redis:alpine'
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - redis
    ports:
      - '3000:3000'
